### PR TITLE
[FIX] requirements: Fix keyword inline_comment_prefixes

### PR DESCRIPTION
**Pull request by moylop260**
Fix Vauxoo/maintainer-quality-tools#221

TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

### CODE REVIEW

**Comment by moylop260** [comment]
@osvalr could you test this PR please?

**Comment by osvalr** [comment]
yes, let me test it

**Comment by osvalr** [comment]
I could not test it, I mean tried to contrast master and this branch and gotten the same result. any hint?

**Comment by moylop260** [comment]
@osvalr the PR was merged and the big image updated
Could you review if was fixed?

**Comment by osvalr** [comment]
@moylop260 tested, it was fixed, thank you!

**Pull request merged**
