### PR TITLE
[FIX] pylint_odoo: Detect the children inside the odoo xml

### PR DESCRIPTION
**Pull request by JesusZapata**
Detect the children inside the odoo xml tag and only active the check `deprecated-data-xml-node` when exist one tag `data` inside de xml

This fix skip the follow case

```xml
<odoo>
    <data noupdate="1">
        <record></record>
    </data>
    <record></record>
</odoo>
```

Fix https://github.com/Vauxoo/pylint-odoo/issues/128

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
This is a small change to avoid false positives

**Comment by moylop260** [comment]
I'm not sure that this is a valid xml for odoo.
I mean, official documentation talk us about use both.

Could you check if odoo use the noupdate correctly for this case?

**Comment by JesusZapata** [comment]
@moylop260 
In the documentation of [odoo](https://www.odoo.com/documentation/10.0/reference/guidelines.html#xml-files) I can't no see noting related with the use of `noupdate` 

Only see the follow help related to `noupdate` 
`The tag <data> is only used to set not-updatable data with noupdate=1`

And I found the same behavior on the odoo code

https://github.com/odoo/odoo/blob/55b8a454c97020fa52799651c3312fcebb3ee5d3/addons/sales_team/data/sales_team_data.xml#L14-L23

https://github.com/odoo/odoo/blob/55b8a454c97020fa52799651c3312fcebb3ee5d3/addons/marketing_campaign/security/marketing_campaign_security.xml#L13-L16

https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/mass_mailing/security/mass_mailing_security.xml#L13-L17

https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/im_livechat/security/im_livechat_channel_security.xml#L20-L25

**Comment by JesusZapata** [comment]
@moylop260 

I run this change over the module of odoo [sales_team](https://github.com/odoo/odoo/tree/saas-17/addons/sales_team)

Without this change the output is the follow
image
The pylint-odoo detect four files



- [addons/sales_team/security/sales_team_security.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/security/sales_team_security.xml#L44-L49) **False positive**
- [addons/sales_team/views/crm_team_views.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/views/crm_team_views.xml#L2-L5)
- [addons/sales_team/data/sales_team_demo.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/data/sales_team_demo.xml#L19-L22)
- [addons/sales_team/data/sales_team_data.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/data/sales_team_data.xml#L14-L18) **False positive**

After apply this change over the code the output is the follow
image
The pylint-odoo detect two files

- [addons/sales_team/views/crm_team_views.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/views/crm_team_views.xml#L2-L5)
- [addons/sales_team/data/sales_team_demo.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/data/sales_team_demo.xml#L19-L22)

**Comment by moylop260** [comment]
Could you create the OCA's PR, please?
I'll update this project after merge

**Comment by JesusZapata** [comment]
I will close this pull request because the pull request in the OCA was merged https://github.com/OCA/pylint-odoo/pull/156 and the change is in the Vauxoo since https://github.com/Vauxoo/pylint-odoo/commit/43a5af59104e9a8cb79396fafde74047acc37522

**Pull request closed without merging**
