### PR TITLE
[IMP] Update pylint==2.0.0 and astroid==1.5.0

### PR DESCRIPTION
**Pull request by lescobarvx**
[IMP] Update pylint==2.0.0 and astroid==1.5.0

### CODE REVIEW

**Comment by lescobarvx** [comment]
@moylop260 
Backward compatibility is ready and works in my local with both versions (pylint 2.0.0 & astroid 1.5.0 / pylint 1.4.4 & astroid 1.3.8) but for some reason travis is processing 2 times the methods "visit_xxx" that I fixed it

**Comment by moylop260** [comment]
Maybe you can define the new methods from init with a if... To avoid this error

**Comment by moylop260** [comment]
Add a tox to test 2 environments

**Comment by moylop260** [comment]
PR to OCA, please

**Comment by lescobarvx** [comment]
@moylop260 
PR to OCA ready!

**Pull request merged**
